### ISSUE TITLE
[FEAT] :sparkles: Create 404 page

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/frontend#28]
### Description

We need to create a `404` not found page

### Design

![404](https://user-images.githubusercontent.com/59249490/194043520-1322a903-d076-42c5-b95c-fa3debbed273.jpg)

### Figma Link -> get the 404 image here (export it as a svg file)

https://www.figma.com/file/Rs1m6fds2FcKauKOhhqfyz/MultiEmail?node-id=0%3A1

**Comment by Kunalpal215** [comment]
can you assign it to me ?

**Comment by aayushchugh** [comment]
@Kunalpal215 let us finalise the design first than you can work on this

**Comment by B1TSH3LL** [comment]
can you assign this to me ???

**Comment by KanLSK** [comment]
> can you assign this to me ???

sure, you can check the design that i just added at the top

**Comment by KanLSK** [comment]
> can you assign it to me ?

Sure, you can check the design i just added at the top

**Comment by Kunalpal215** [comment]
I have created pull request can you please look at it ?

**Comment by KanLSK** [comment]
> I have created pull request can you please look at it ?
please use tailwindCSS instead if vanilla CSS and also use the svg image instead of png

**Comment by Kunalpal215** [comment]
I have created new PR now
