### ISSUE TITLE
[BUG] :bug: edit issue template config to submit empty issues

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/frontend#35]
### Current Behaviour

We can't create any empty issues

### Expected Behaviour

we should be able to submit empty issues

### Anything else?

in `./github/ISSUE_TEMPLATE/config.yml` use this code 

```yml
blank_issues_enabled: true
```

**Comment by KOQ-UTx10101** [comment]
Hi again @aayushchugh can I complete this task too ?

**Comment by KOQ-UTx10101** [comment]
Thanks
