### ISSUE TITLE
[FEAT] :sparkles: Setup Docker

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/frontend#36]
### Description

we need to configure docker for this application

- [ ] setup docker
- [ ] update readme and mention all the steps on how to use docker for the project 

### Anything else?

take reference for reamde from [backend repo](https://github.com/MultiEmail/backend/blob/main/README.md)

**Comment by KOQ-UTx10101** [comment]
Hi @aayushchugh I am a DevOps Expert contributing to Hacktoberfest. I would like to work on this issue please assign me to it.

Thanks

**Comment by aayushchugh** [comment]
@KOQ-UTx10101 sure

**Comment by aayushchugh** [comment]
@KOQ-UTx10101 this issue is getting re-assigned to @tharun634

**Comment by KOQ-UTx10101** [comment]
ok but I have completed it so should I not make a pull request now ?

**Comment by aayushchugh** [comment]
@KOQ-UTx10101 If you have completed than please create a PR
