### ISSUE TITLE
[FEAT] :sparkles: Validation for signup form

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/frontend#43]
### Description

Need to add validation on signup form for following fields

- username
	- required
	- should not be shorter than 3 characters
	- should not be longer than 50 characters
		
- email
	- required
	- should be a valid email

- password
	- required
	- minimum length of 6 characters

- cpassword
	- required
	- minimum length of 6 characters
	- password and cpassword should be same

### Anything else?

file:- `/src/pages/signup/Signup.tsx`
library:- use [zod](https://zod.dev/) for validation

**Comment by kala2** [comment]
hey can i take this one?

**Comment by aayushchugh** [comment]
@kala2 We have to use [zod](https://zod.dev/) for validation

**Comment by aayushchugh** [comment]
@MultiEmail/frontend-developers can anyone work on this issue?

**Comment by KanLSK** [comment]
> @MultiEmail/frontend-developers can anyone work on this issue?

So @kala2 not working on this issue anymore?

**Comment by aayushchugh** [comment]
@KanLSK I don't think he is working on this one

**Comment by kala2** [comment]
Sorry for late response, you can take this one

**Comment by is-it-ayush** [comment]
Closed! Issue was solved in #91
