### ISSUE TITLE
[FEAT] :sparkles: Add hover effect on back button in login and signup page

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/frontend#54]
### Description

We can change colour of the back arrow on hover

### Anything else?

![Recording 2022-10-07 at 13 28 49](https://user-images.githubusercontent.com/69336518/194503145-63654862-ee05-45c2-92c5-a7dc6eb6d8b2.gif)

**Comment by debopriyadey** [comment]
assign it to me, ill be more than pleased to assist

**Comment by aayushchugh** [comment]
@debopriyadey Go ahead
