### ISSUE TITLE
[REFACTOR] :recycle: Create new variable for colors in tailwind

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/frontend#55]
### Description

Instead of using `text-[#3F72AF]` everywhere we can create custom variable in `tailwind.config` file

also create variables for all colours used in [figma design](https://www.figma.com/file/Rs1m6fds2FcKauKOhhqfyz/MultiEmail?node-id=0%3A1)

### Anything else?

![image](https://user-images.githubusercontent.com/69336518/194506087-4ca9035f-ca11-4b51-b4bd-c5e7fc417829.png)

**Comment by KanLSK** [comment]
I’ll do this once i get back home on sunday

**Comment by 0hundred0** [comment]
I can knock this out tonight. I might need a break from Go practice lol.
