### ISSUE TITLE
[FEAT] :sparkles: If access token is expired than it should auto refresh

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/frontend#58]
### Description

`access_token` will be automatically refreshed if it's expired

**Comment by corners2wall** [comment]
@aayushchugh, assign to me pls. I will try. 
I need call `/auth/refresh` after expired error on any request, sure?

**Comment by aayushchugh** [comment]
@corners2wall thanks for showing interest but I am currently working on this one, so can work on another issues

You can also join our [discord server](https://discord.gg/gkvCYzRKEB)
