### ISSUE TITLE
[FEAT] :sparkles: <Ask the user for permission to send marketing emails when registering>

### ISSUE THREAD

**Issue by Karol-Ari** [MultiEmail/frontend#65]
### Description

Add a radio button to ask the user for permission to send marketing mail 

![image](https://user-images.githubusercontent.com/55296886/194645714-0a265640-a87c-4044-a45a-5f7a4be0f2c9.png)

**Comment by lolbroek2007** [comment]
Can I take this one? And Wdym with ratio button?

**Comment by Karol-Ari** [comment]
> Can I take this one? And Wdym with ratio button?

Yes you can.

**Comment by is-it-ayush** [comment]
Hi @lolbroek2007. Are you still working on it?

**Comment by lolbroek2007** [comment]
Sorry lost intrest

**Comment by is-it-ayush** [comment]
Alright! Thank You.
