### ISSUE TITLE
[FEAT] :sparkles: User can login wiith either `username` or `email`

### ISSUE THREAD

**Issue by aayushchugh** [MultiEmail/frontend#92]
### Description

Update the input on login page to let user login with email or username

we can add regex validation on the input value and if it contains an `@` than it's email
otherwise it's `username`

### Anything else?

Wait for #91 to merge and then start working on it

**Comment by whyang0808** [comment]
Hi, can I work on this?

**Comment by snikoletopoulos** [comment]
Hello, I would love to contribute to this one
I see there is already formik and yup, we could use these to validate the input (if it is email or username)
